# Generated by Django 5.2.3 on 2025-07-02 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('I', 'FORM I'), ('II', 'FORM II'), ('III', 'FORM III'), ('IV', 'FORM IV'), ('v', 'FORM V'), ('VI', 'FORM VI')], max_length=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Assigned teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
